### ISSUE TITLE
IDAES site access

### ISSUE THREAD

**Issue by tony121psu** [IDAES/idaes.github.io#1]
Hello. This is Tony Burgard from NETL. I'm working with David, John, Andrew, Miguel, etc. Is there anything special I need to do to gain access to the IDAES github site?

Much thanks,
Tony

**Comment by ksbeattie** [comment]
Tony,

It looks like you have a github account already as user tony121psu, is
that you?

If so, I'll add you as a member of the team on github.

ksb

**Comment by tony121psu** [comment]
Yes. That’s me. It’d be great if you could add me.

Thanks!
--Tony

**Comment by blnicho** [comment]
This is Bethany Nicholson from Sandia. I'm a new member to the IDAES team working on dynamic model extensions in Pyomo. Could I also get access to the github site? My username is blnicho.

Thanks!
Bethany

**Comment by ksbeattie** [comment]
I believe both of you have (and have for some time now) access to the IDAES org and repos.

**Comment by santiagoropb** [comment]
This is Santiago Rodriguez from Purdue University. I'm a new member to the IDAES team and I work with Dr. Carl Laird on parallel algorithms for dynamic optimization. Could I also get access to the github site? My username is blnicho.

Thanks!
Santiago

**Comment by qtothec** [comment]
@santiagoropb I am confused by your username.
